tags: "jazz pop, soft jazz, female vocal, calm, melancholic, piano-driven, intimate"
lyrics: |
  I waited 'til I saw the sun
  I don't know why I didn't come
  I left you by the house of fun
  Don't know why I didn't come
  Don't know why I didn't come
